name: Reusable - Deploy to EC2

# This workflow is triggered when called by another workflow
on:
  workflow_call:

jobs:
  deploy-to-ec2:
    name: Deploy to EC2 Instances
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      # Step 2: Use the AWS CLI directly to send the deployment command.
      - name: Execute deployment script on EC2 instances via AWS CLI
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets '[{"Key":"tag:Deployment","Values":["hello-world-app"]}]' \
            --parameters '{
              "commands":[
                "cd /home/ec2-user/app",
                "aws ecr get-login-password --region us-east-2 | sudo docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_REPO_URL }}",
                "echo \"version: ''3.7''\\nservices:\\n  web:\\n    image: ${{ secrets.AWS_ECR_REPO_URL }}:latest\\n    ports:\\n      - ''3000:3000''\\n    healthcheck:\\n      test: [\\\"CMD\\\", \\\"curl\\\", \\\"-f\\\", \\\"http://localhost:3000/health\\\"]\\n      interval: 30s\\n      timeout: 10s\\n      retries: 3\" > docker-compose.yml",
                "sudo /usr/local/bin/docker-compose pull",
                "sudo /usr/local/bin/docker-compose up -d --force-recreate"
              ]
            }'